version: '3.9'
services:
  redis0:
    image: redis:6.2-alpine
    container_name: redis0
    networks:
      dds-network:
        ipv4_address: 172.26.0.99
  endorser0:
    image: jc/dds-it-dlp-endorser
    ports:
      - "8090:8090"
    environment:
      - ENDORSER_ID=0
      - PORT=8090
      - SPRING_PROFILES_ACTIVE=endorser,tls
    networks:
      dds-network:
        ipv4_address: 172.26.0.21
  service0:
    image: jc/dds-it-dlp
    depends_on:
      - redis0
    ports:
      - "8080:8080"
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=0
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=service,redis,tls
      - CONSENSUS=bftsmart
    networks:
      dds-network:
        ipv4_address: 172.26.0.20
  bft0:
    image: jc/dds-it-dlp
    depends_on:
      - redis0
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=0
      - SPRING_PROFILES_ACTIVE=bft,redis
    networks:
      dds-network:
        ipv4_address: 172.26.0.2
  redis1:
    image: redis:6.2-alpine
    container_name: redis1
    networks:
      dds-network:
        ipv4_address: 172.26.1.99
  endorser1:
    image: jc/dds-it-dlp-endorser
    ports:
      - "8091:8091"
    environment:
      - ENDORSER_ID=1
      - PORT=8091
      - SPRING_PROFILES_ACTIVE=endorser,tls
    networks:
      dds-network:
        ipv4_address: 172.26.0.31
  service1:
    image: jc/dds-it-dlp
    depends_on:
      - redis1
    ports:
      - "8081:8081"
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=1
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=service,redis,tls
      - CONSENSUS=bftsmart
    networks:
      dds-network:
        ipv4_address: 172.26.0.30
  bft1:
    image: jc/dds-it-dlp
    depends_on:
      - redis1
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=1
      - SPRING_PROFILES_ACTIVE=bft,redis
    networks:
      dds-network:
        ipv4_address: 172.26.0.3
  redis2:
    image: redis:6.2-alpine
    container_name: redis2
    networks:
      dds-network:
        ipv4_address: 172.26.2.99
  endorser2:
    image: jc/dds-it-dlp-endorser
    ports:
      - "8092:8092"
    environment:
      - ENDORSER_ID=2
      - PORT=8092
      - SPRING_PROFILES_ACTIVE=endorser,tls
    networks:
      dds-network:
        ipv4_address: 172.26.0.41
  service2:
    image: jc/dds-it-dlp
    depends_on:
      - redis2
    ports:
      - "8082:8082"
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=2
      - PORT=8082
      - SPRING_PROFILES_ACTIVE=service,redis,tls
      - CONSENSUS=bftsmart
    networks:
      dds-network:
        ipv4_address: 172.26.0.40
  bft2:
    image: jc/dds-it-dlp
    depends_on:
      - redis2
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=2
      - SPRING_PROFILES_ACTIVE=bft,redis
    networks:
      dds-network:
        ipv4_address: 172.26.0.4
  redis3:
    image: redis:6.2-alpine
    container_name: redis3
    networks:
      dds-network:
        ipv4_address: 172.26.3.99
  endorser3:
    image: jc/dds-it-dlp-endorser
    ports:
      - "8093:8093"
    environment:
      - ENDORSER_ID=3
      - PORT=8093
      - SPRING_PROFILES_ACTIVE=endorser,tls
    networks:
      dds-network:
        ipv4_address: 172.26.0.51
  service3:
    image: jc/dds-it-dlp
    depends_on:
      - redis3
    ports:
      - "8083:8083"
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=3
      - PORT=8083
      - SPRING_PROFILES_ACTIVE=service,redis,tls
      - CONSENSUS=bftsmart
    networks:
      dds-network:
        ipv4_address: 172.26.0.50
  bft3:
    image: jc/dds-it-dlp
    depends_on:
      - redis3
    environment:
      - REDIS_PORT=6379
      - REPLICA_ID=3
      - SPRING_PROFILES_ACTIVE=bft,redis
    networks:
      dds-network:
        ipv4_address: 172.26.0.5
networks:
  dds-network:
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1